---
name: "Setup system for robenv"
description: "Installs system dependencies necessary to run robenv"
runs:
    using: composite
    steps:
        - name: Installations
          shell: bash
          run: |
              sudo apt-get update
              sudo apt-get install --yes --no-install-recommends \
                  fakeroot debhelper dh-python
