---
name: CI

on: [push, pull_request]

jobs:
    lock_file_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-poetry
            - uses: ./.github/actions/dependency-install

            - name: Check lock file
              run: poetry check --lock

    formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-poetry
            - uses: ./.github/actions/dependency-install

            - name: Formatting
              run: ./ci-format.py --check

    typing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-poetry
            - uses: ./.github/actions/dependency-install

            - name: Typing
              run: ./ci-typing.py

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-poetry
            - uses: ./.github/actions/dependency-install

            - name: Linting
              run: ./ci-lint.py --check

    unit_test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                container:
                    - ros:noetic-ros-base
                    - ros:iron-ros-base
        container: ${{ matrix.container }}
        steps:
            - uses: actions/checkout@v3
            - run: apt-get update
            - run: |
                apt-get --yes --no-install-recommends install \
                curl \
                fakeroot \
                debhelper \
                dh-python \
                python-is-python3

            - uses: ./.github/actions/setup-poetry
              with:
                  python-version: "system"
            - uses: ./.github/actions/dependency-install

            - name: Unit Tests
              run: ./ci-unit-test.py

    integration_test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                container:
                    - ros:noetic-ros-base
                    - ros:iron-ros-base
        container: ${{ matrix.container }}
        steps:
            - uses: actions/checkout@v3
            - run: apt-get update
            - run: |
                apt-get --yes --no-install-recommends install \
                curl \
                debhelper \
                dh-python \
                fakeroot \
                python-is-python3

            - uses: ./.github/actions/setup-poetry
              with:
                  python-version: "system"
            - uses: ./.github/actions/dependency-install

            - name: Integration Tests
              run: ./ci-integration-test.py

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-poetry
            - uses: ./.github/actions/dependency-install

            - name: Build
              run: poetry build
